geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
"""geekshop URL Configuration

The `urlpatterns` list routes URLs to templates. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function templates
    1. Add an import:  from my_app import templates
    2. Add a URL to urlpatterns:  path('', templates.home, name='home')
Class-based templates
    1. Add an import:  from other_app.templates import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from geekshop import settings


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.conf.urls.static import static
from django.urls import path
import mainapp.views as mainapp
from geekshop import settings


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:pk>/', mainapp.products, name='category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveSmallIntegerField(verbose_name='age')
# Create your models here.

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):

    name = models.CharField(max_length=64)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"





# Create your models here.

geekshop/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'email', 'first_name', 'age', 'avatar', 'password1', 'password2')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'email', 'first_name', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'password':
                field.widget = forms.HiddenInput()

geekshop/authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from django.urls import reverse


def login(request):

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {
        'title': 'Login',
        'login_form': login_form,
    }

    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {
        'title': 'Sign Up',
        'register_form': register_form,
    }

    return render(request, 'authapp/register.html', content)


def edit(request):
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm()

    content = {
        'title': 'Edit',
        'edit_form': edit_form,
    }

    return render(request, 'authapp/edit.html', content)

# Create your views here.

geekshop/mainapp/views.py
from datetime import datetime
from django.shortcuts import render
from mainapp.models import Product, ProductCategory


def main(request):

    products = Product.objects.all()
    context = {
        'title': 'Главная',
        'date': datetime.now(),
        'products': products[:4]
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None):
    links_menu = ProductCategory.objects.all()
    context = {
        'title': 'Товары',
        'date': datetime.now(),
        'links_menu': links_menu
    }
    return render(request, 'mainapp/products.html', context)


def contact(request):
    context = {
        'title': 'Контакты',
        'date': datetime.now()
    }
    return render(request, 'mainapp/contact.html', context)

# Create your templates here.

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input type="submit" value="Save" class="form-control"/>
    </form>
<br>
    <button class="btn btn-link form-control">
        <a href="{% url 'main' %}">Main page</a>
    </button>
    <div>
        <img src="/media/{{ user.avatar }}" alt="avatar">
    </div>
{% endblock %}

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <input type="submit" value="Login" class="form-control"/>
    </form>
<br>
    <button class="btn btn-link form-control">
        <a href="{% url 'auth:register' %}">Sign up</a>
    </button>
{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <input type="submit" value="Sign Up" class="form-control"/>
    </form>
<br>
    <button class="btn btn-link form-control">
        <a href="{% url 'auth:login' %}">Log In</a>
    </button>
{% endblock %}

geekshop/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}

	</div>

    {% block footer %}
        <div class="footer">
            <div class="text-footer">
               <h3>контакты</h3>{{ date|date:"Y" }}
            </div>
            <div class="text-footer">
               <h3>полезная информация</h3>

            </div>

        </div>
    {% endblock %}

</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="hero">
            <div class="header clearfix">
                <a href="index.html" class="logo"></a>
                <ul class="menu">
                    {% include 'mainapp/includes/inc_main_menu.html' %}
                </ul>
                <a href="#" class="search"></a>
                <a href="#" class="basket"></a>
            </div>
            <h1>наши контакты</h1>
        </div>

        <div class="location">
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>Москва</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>+7-888-888-8888</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>info@geekshop.ru</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>В пределах МКАД</p>
                </div>
            </div>
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>Москва</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>+7-888-888-8888</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>info@geekshop.ru</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>В пределах МКАД</p>
                </div>
            </div>
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>Москва</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>+7-888-888-8888</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>info@geekshop.ru</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>В пределах МКАД</p>
                </div>
            </div>
        </div>

        <div class="clr"></div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}"
               class="{% if products in request.resolver_match.url_name == link.href %}
                        active
                      {% endif %}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<li>
    <a href="{% url 'main' %}"
       class="{% if request.resolver_match.url_name == 'main' %}
                        active
              {% endif %}">
        домой
    </a>
</li>
<li>
    <a href="{% url 'products:products' %}"
       class="{% if 'products' in request.resolver_match.url_name %}
                        active
              {% endif %}">
        продукты
    </a>
</li>
<li>
    <a href="{% url 'contact' %}"
       class="{% if request.resolver_match.url_name == 'contact' %}
                        active
              {% endif %}">
        контакты
    </a>
</li>

    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'auth:edit' %}"
           class="{% if request.resolver_match.url_name == 'profile' %}
                            active
                  {% endif %}">
            {{ user.first_name|default:'Profile' }}
        </a>
    </li>
    <li>
        <a href="{% url 'auth:logout' %}">
            Log Out
        </a>
    </li>
    {% else %}
    <li>
        <a href="{% url 'auth:login' %}">
            Log In
        </a>
    </li>
    {% endif %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
	<div class="slider">
		<div class="header clearfix">
			<a href="index.html" class="logo"></a>
			<ul class="menu">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</ul>
			<a href="#" class="search"></a>
		</div>
		<div class="text-slider">
			<h3 class="green">тенденции</h3>
			<h3 class="big"> удобные стулья</h3>
			<p>Новый уровень комфорта. Отличные характеристики.</p>
			<a href="#" class="button-order">заказать <img src="{% static '/img/arrow.png' %}" alt=""></a>
		</div>
		<div class="navi">
			<a href="#"></a><a href="#"></a><a href="#"></a>
		</div>
	</div>

	<div class="featured">
		<div class="featured-menu">
			<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
		</div>
		<a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>
		<div class="clearfix">
		</div>
		<div class="tab-content">
			{% for product in products %}
				<div class="block">
					<a href="#">
						<img src="/media/{{ product.image }}" alt="{{product.name}}">
						<div class="text">
							<img src="{% static '/img/icon-hover.png' %}" alt="{{product.name}}">
							<h4>{{ product.name }}</h4>
							<p>{{ product.short_desc }}</p>
						</div>
					</a>
				</div>
			{% endfor %}

		</div>
	</div>

	<div class="clr"></div>

	</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="container">
		<div class="hero-white">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					{% include 'mainapp/includes/inc_main_menu.html' %}
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static '/img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static '/img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll1.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static '/img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static '/img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static '/img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static '/img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static '/img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static '/img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static '/img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>	
{% endblock %}